create table event_booking (id bigint generated by default as identity, event_id varchar(255) not null, conference_id varchar(255) not null, fully_booked boolean, number_occupied integer, version integer, primary key (id));
alter table event_booking add constraint UK_i963nubbo8eo5pc5i6rjygx9a unique (conference_id, event_id);
