#%RAML 0.8
---
title: "Duke Conference App"
version: "1.0.0"
baseUri: "http://dukecon.org"

schemas:
  - Talks: !include talks_schema.json
  - MetaData: !include meta_schema.json

/talks:
  get:
    description: "Receive all talks"
    responses:
      200:
        description: "Success"
        body:
          application/json:
            schema: "Talks"
            example: !include talks_example.json

/meta:
  get:
    description: "Receive Meta information"
    responses:
      200:
        description: "Success"
        body:
          application/json:
            schema: "MetaData"
            example: !include meta_example.json
